/**
 * Dashboard / Overview Types
 *
 * Shared types for the AI-powered project overview dashboard.
 * Used by server (generation), UI (display), and chat (display).
 */

// ---------------------------------------------------------------------------
// Time Range
// ---------------------------------------------------------------------------

/** Available time range presets for the dashboard */
export type DashboardTimeRange = '12h' | '24h' | '4d' | '1w';

// ---------------------------------------------------------------------------
// Data Collection Types (server-side input)
// ---------------------------------------------------------------------------

/** A markdown file collected for the overview prompt */
export interface OverviewMarkdownData {
  /** Relative path within the project */
  path: string;
  /** File name */
  name: string;
  /** Last modified timestamp (ms since epoch) */
  modified: number;
  /** First N lines of content (preview) */
  preview: string;
  /** File size in bytes */
  size: number;
}

/** Git data collected for the overview prompt */
export interface OverviewGitData {
  /** Whether git is available for this project */
  available: boolean;
  /** Parsed commit list (newest first) */
  commits: OverviewGitCommit[];
  /** Total number of commits found (before limit) */
  totalCommits: number;
}

/** A single git commit */
export interface OverviewGitCommit {
  hash: string;
  message: string;
  author: string;
  date: string;
}

// ---------------------------------------------------------------------------
// Overview Result Types
// ---------------------------------------------------------------------------

/** Which generation mode was used */
export type DashboardMode = 'standard' | 'simplify' | 'detail';

/** Options for generating an overview */
export interface GenerateOverviewOptions {
  mode?: DashboardMode;
  modelOverride?: string;
}

/** A single work section (e.g. "Backend", "Frontend", "Tests") */
export interface DashboardSection {
  title: string;
  items: DashboardItem[];
}

/** An individual change or activity item */
export interface DashboardItem {
  text: string;
  /** Optional file or path reference */
  file?: string;
}

/** Suggested improvement */
export interface DashboardImprovement {
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high';
}

/** Security-related finding */
export interface DashboardSecurityItem {
  title: string;
  description: string;
  severity: 'info' | 'warning' | 'critical';
}

/** Numeric stats about the analysed time range */
export interface DashboardStats {
  filesChanged: number;
  commits: number;
  linesAdded: number;
  linesRemoved: number;
}

/** Meta information about the generation run */
export interface DashboardMetadata {
  gitAvailable: boolean;
  filesAnalysed: number;
  truncated: boolean;
  durationMs: number;
}

/** Full overview data generated by the backend */
export interface DashboardOverviewData {
  timeRange: DashboardTimeRange;
  generatedAt: string;
  model: string;
  mode: DashboardMode;
  summary: string;
  sections: DashboardSection[];
  improvements: DashboardImprovement[];
  security: DashboardSecurityItem[];
  stats: DashboardStats;
  metadata: DashboardMetadata;
}

// ---------------------------------------------------------------------------
// Overview Status (for GET /api/overview/status)
// ---------------------------------------------------------------------------

export interface OverviewStatusEntry {
  exists: boolean;
  generatedAt?: string;
}

export type OverviewStatusMap = Record<DashboardTimeRange, OverviewStatusEntry>;

// ---------------------------------------------------------------------------
// Time Range Constants & Helpers
// ---------------------------------------------------------------------------

export interface DashboardTimeRangeOption {
  id: DashboardTimeRange;
  label: string;
  hours: number;
}

export const DASHBOARD_TIME_RANGES: DashboardTimeRangeOption[] = [
  { id: '12h', label: '12h', hours: 12 },
  { id: '24h', label: '24h', hours: 24 },
  { id: '4d', label: '4 Tage', hours: 96 },
  { id: '1w', label: '1 Woche', hours: 168 },
];

/** Get the hours for a given time range id */
export function getTimeRangeHours(id: DashboardTimeRange): number {
  return DASHBOARD_TIME_RANGES.find((r) => r.id === id)?.hours ?? 24;
}
