// ---------------------------------------------------------------------------
// Dashboard / Overview Types
// ---------------------------------------------------------------------------

/** Available time range presets for the dashboard */
export type DashboardTimeRange = '12h' | '24h' | '4d' | '1w';

/** Which generation mode was used */
export type DashboardMode = 'standard' | 'simplify' | 'detail';

/** A single work section (e.g. "Backend", "Frontend", "Tests") */
export interface DashboardSection {
  title: string;
  items: DashboardItem[];
}

/** An individual change or activity item */
export interface DashboardItem {
  text: string;
  /** Optional file or path reference */
  file?: string;
}

/** Suggested improvement */
export interface DashboardImprovement {
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high';
}

/** Security-related finding */
export interface DashboardSecurityItem {
  title: string;
  description: string;
  severity: 'info' | 'warning' | 'critical';
}

/** Numeric stats about the analysed time range */
export interface DashboardStats {
  filesChanged: number;
  commits: number;
  linesAdded: number;
  linesRemoved: number;
}

/** Meta information about the generation run */
export interface DashboardMetadata {
  gitAvailable: boolean;
  filesAnalysed: number;
  truncated: boolean;
  durationMs: number;
}

/** Full overview data generated by the backend */
export interface DashboardOverviewData {
  timeRange: DashboardTimeRange;
  generatedAt: string; // ISO timestamp
  model: string;
  mode: DashboardMode;
  summary: string;
  sections: DashboardSection[];
  improvements: DashboardImprovement[];
  security: DashboardSecurityItem[];
  stats: DashboardStats;
  metadata: DashboardMetadata;
}

// ---------------------------------------------------------------------------
// Time range constants
// ---------------------------------------------------------------------------

export interface DashboardTimeRangeOption {
  id: DashboardTimeRange;
  label: string;
  hours: number;
}

export const DASHBOARD_TIME_RANGES: DashboardTimeRangeOption[] = [
  { id: '12h', label: '12h', hours: 12 },
  { id: '24h', label: '24h', hours: 24 },
  { id: '4d', label: '4 Tage', hours: 96 },
  { id: '1w', label: '1 Woche', hours: 168 },
];

/** Get the hours for a given time range id */
export function getTimeRangeHours(id: DashboardTimeRange): number {
  return DASHBOARD_TIME_RANGES.find((r) => r.id === id)?.hours ?? 24;
}
